dist: precise
sudo: required
language: ruby

install:
 - sudo apt-get purge virtualbox-dkms
 - sudo apt-get purge virtualbox
 - sudo apt-get install -y -q virtualbox-dkms
 - sudo apt-get install -y -q linux-headers-generic
 - sudo apt-get install -y -q virtualbox
 - sudo apt-get install -y -q vagrant

script:
 - VBoxManage --version
 - cd ./vagrant
 - vagrant package --base neil-dev-vm
