dist: trusty
sudo: required
language: ruby

install:
 - sudo apt-get purge virtualbox virtualbox-dkms
 - sudo apt-get install -y -q virtualbox-dkms linux-headers-generic virtualbox vagrant

script:
 - VBoxManage --version
 - cd ./vagrant
 - vagrant package --base neil-dev-vm
