dist: precise
sudo: required
language: ruby

install:
 - echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" >  
 - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
 - sudo apt-get purge virtualbox
 - sudo apt-get update
 - sudo apt-get install -y virtualbox-5.0 dkms
 - sudo apt-get install -y -q vagrant

script:
 - VBoxManage --version
 - cd ./vagrant
 - vagrant package --base neil-dev-vm
