dist: trusty
sudo: required
language: ruby

install:
  sudo apt-get install -y -q linux-headers-generic vagrant virtualbox virtualbox-dkms

script:
 - VBoxManage --version
 - cd ./vagrant
 - vagrant package --base neil-dev-vm
