dist: trusty
sudo: required
language: ruby

install:
  sudo apt-get install -y -q linux-headers-generic virtualbox-dkms virtualbox vagrant

script:
 - VBoxManage --version
 - cd ./vagrant
 - vagrant package --base neil-dev-vm
